version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: dev-redis-survey
    ports:
      - "6379:6379"
    volumes:
      - redis-data-survey:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  redis-data-survey:
